---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r, results="hide", echo=FALSE}
library(dplyr)
library(plyr)
library(ggplot2)
library(reshape2)
```
## Loading and preprocessing the data
```{r}
data<- read.csv("activity.csv")
dates<- group_by(data, date)

```
## What is mean total number of steps taken per day?
```{r}
hist(data$steps, breaks= 50, main="Frequency of Steps Histogram", xlab="Number of Daily Steps")
stmean<- mean(data$steps, na.rm=T)
stmean
stmedian<- median(data$steps, na.rm=T)
stmedian
```
## What is the average daily activity pattern?
```{r}
dates<- group_by(data, interval)
intsum<- summarise(dates, mean=mean(steps, na.rm=T), median=median(steps, na.rm=T))
```
##```{r}
qplot(data=intsum, x=interval, y=mean,  geom="line",main="Mean Steps by Daily Interval", xlab="Daily Interval", ylab="Mean Number of Steps")
abline(v=835, col="red")
intsum$interval[which.max(intsum$mean)]
##```

## Imputing missing values
### Number of missing values
```{r}
Nas<-sum(is.na(data$steps))
Nas
```
### Impute NA value based on mean value for that interval
```{r}
impute.mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
imp1 <- ddply(data, ~ interval, transform, steps = impute.mean(steps))

hist(imp1$steps, breaks= 50, main="Frequency of Steps Histogram", xlab="Number of Daily Steps")
stmean1<- mean(imp1$steps, na.rm=T)
stmean1
stmedian1<- median(imp1$steps, na.rm=T)
stmedian1
```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
data$date<- as.Date(data$date)
is.weekend <- function(x) ((as.numeric(x)-2) %% 7) < 2
data$week<- ifelse(is.weekend(data$date)==TRUE, "weekday", "weekend")
data$week<- as.factor(data$week)
par(mfrow = c(2, 1), type="l")
 plot(dataW$interval, dataW$steps, type="l")
 plot(dataD$interval, dataD$steps, type="l")
)
```